language: java
jdk:
  - oraclejdk8
  
# npm install runs by default but shown here for illustrative purposes
#before_install:
#    - npm install chromedriver
    
install: #ant deps

   - wget https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
   - unzip chromedriver_linux64.zip
   - sudo apt-get install libnss3
   - sudo apt-get --only-upgrade install chromium-browser
   - sudo cp chromedriver /usr/local/bin/.
   - sudo chmod +x /usr/local/bin/chromedriver

#script: xvfb-run npm run travis
   
before_script:
  - "export DISPLAY=:99.0"
  - xvfb-run npm run travis
  #- "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start