sudo: true

language: java

jdk:
    - oraclejdk8

os:
    - linux

install: 
   #- wget https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
   - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
   #- unzip chromedriver_linux64.zip
   - tar -vzxf geckodriver-v0.15.0-linux64.tar.gz
   - sudo apt-get install libnss3
   - sudo apt-get --only-upgrade install firefox
   #- sudo cp chromedriver /usr/local/bin/.
   - sudo cp geckodriver /usr/local/bin/.
   #- sudo chmod +x /usr/local/bin/chromedriver
   - sudo chmod +x /usr/local/bin/geckodriver

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start



  