language: java
jdk:
  - oraclejdk8
  
# npm install runs by default but shown here for illustrative purposes
#before_install:
#    - npm install chromedriver
    
install: 
#ant deps
    - wgets https://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - sudo apt-get --only-upgrade install google-chrome-stable
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver